### ISSUE TITLE
1.5.3 Zigbee remove device removes wrong device

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#113]
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**
For example: 1 device is paired, then i try to add an other one, it says already  paired, so i try to remove device 2, then it removes devices 1

*Please include detailed steps how we can reproduce the issue*
Add 1 zigbee device (i used hue motion sensor)
Add zigbee device 2  (i used hue motion sensor) and get message device already paired
remove device -> instellingen -> zigbee -> verwijder device
set device 2 to pair mode
homey deletes device 1 and in zigbee you get unknown device

**What was the result?**
it deleted device 1
...

**What did you expect as result?**
if i  delete device 2 by   pair device 2, it should delete that one, not an other one
...

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
Fixed in 1.5.4-rc.1, can you confirm?

**Comment by robiebab** [comment]
Bug is still there in 1.5.6 rc3

try and remove a zigbee device (homey deltes always an other)

**Comment by RobinBol** [comment]
This issue is caused by the battery device which you paired first still keeps sending association commands to Homey. Try to reset your zigbee network, or remove all devices, and after pairing the first motion sensor remove the battery (after waiting a bit), then pair the second one, and afterwards put the battery back in the first device.

**Comment by robiebab** [comment]
Hi Robin,

this is more a leftover bug-> if i a device is not paired correctly sometimes it is still there as a leftover in the zigbee network (not as device in home). If you remove the device by: instellingen -> zigbee -> verwijder device it removes the wrong one.

p.s. i used the one from kasteleman: https://github.com/kasteleman/nl.philips.zigbee

**Comment by RobinBol** [comment]
@robiebab the next Homey firmware build will automatically remove the 'unknown' ZigBee devices, so removing via Settings > ZigBee -> remove a device will not be necessary. It is only necessary to reset the device and then it can be re-added.

I tested, and when removing the Philips Hue Motion sensor via the devices view it works as expected. Do you agree we can close this issue then? If not, just leave a comment!
