### ISSUE TITLE
[1.5.6] Zigbee mesh not rebuilding

### ISSUE THREAD

**Issue by lubbertkramer** [athombv/homey-issues-dp#157]
**What is your Homey version (Settings → System)?**

1.5.6 (final experimental release)

Stuur de volgende code naar een Athom medewerker:
9BBDC7D4FF

**What did you try to achieve?**

Looking at my Zigbee mesh because of some Zigbee problems. Recently i nicely saw my Zigbee mesh (https://github.com/athombv/homey/issues/2160#issuecomment-361595600) but now i won't see it anymore. Did several reboots / PTP but still no mesh. After latest PTP (15 minutes) now 2 hours have passed and still no mesh

![nomesh](https://user-images.githubusercontent.com/8224586/36357155-2d7ee7a0-14fa-11e8-8f29-303fb32e67ac.PNG)

**What did you expect as result?**

see my zigbee mesh like https://github.com/athombv/homey/issues/2160#issuecomment-361595600

**Any other remarks**

...

**Comment by RobinBol** [comment]
Hi, this week we fixed a bug in the dev tools that could cause the mesh to show as in your screenshot. Please note, depending on your network (and whether or not all devices are turned on) it can take some time (1 - 15 minutes) before the mesh will show.

Could you verify that eventually the mesh will be shown?

**Comment by lubbertkramer** [comment]
Will start reboot now and recheck in 15 minutes. All my Ikea/Hue routers are turned on, put a lasklem between the brown/black wire so they can't be turned off by power

**Comment by lubbertkramer** [comment]
Just did a reboot again, Homey is saying what you will see below and still won't see my mesh, two hours have passed since reboot and still like the picture above.

uptime | 7481

**Comment by lubbertkramer** [comment]
Did a reboot around 00:00 last night so uptime Homey now 36482 according to stuff for geeks but still same picture as post 1

**Comment by RobinBol** [comment]
The mesh starts generating only when you visit the dev tools, did you click the refresh button once and leave the browser window open for half an hour for example? (a loading indication is probably desired, but just to test that the graph will eventually build)

**Comment by lubbertkramer** [comment]
Updated to 1.5.7 24 minutes ago, now have developers tools open, pressed refresh and now i'm waiting :)

**Comment by lubbertkramer** [comment]
Didn't need to wait 30 minutes it's already there. But i guess it's better to report above information also on the page or indeed a sliding bar otherwise i guess a lot of users will keep saying Zigbee is broken :)

**Comment by RobinBol** [comment]
Thanks for reporting! Will look at some loading indication
